terraform {
  required_version = ">= 1.5.0"
  # Remote state in S3 so the state survives between (ephemeral) CI runs — otherwise every run starts
  # blind and collides with the resources the previous run created. Configured at `terraform init`
  # time via -backend-config (bucket/key/region), so nothing account-specific is committed here.
  backend "s3" {}
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

provider "aws" {
  region = var.region
}

# The mesh's OIDC session/state signing key (Benzene.Mesh.Auth.Oidc's MeshOidcOptions.SigningKey) -
# generated by Terraform, never hand-typed, never something a human copies around. Lives only in
# Terraform state and the mesh Lambda's environment variables (below). 44 bytes of randomness
# (base64-encoded, so the actual secret is materially larger than MeshOidcOptions.Validate()'s 32-byte
# floor) - regenerating this (e.g. via `terraform taint`) invalidates every existing session/state
# cookie, which is safe and expected (they just re-login).
resource "random_id" "mesh_oidc_signing_key" {
  byte_length = 44
}

data "aws_caller_identity" "current" {}

locals {
  bucket_name = var.artifact_bucket_name != "" ? var.artifact_bucket_name : "${var.project}-${data.aws_caller_identity.current.account_id}"

  # Benzene.ClaimCheck.Aws.S3's default key prefix (Benzene.ClaimCheck.Aws.S3/Extensions.cs's
  # DefaultPrefix) — orders-api/payments-api register the store with no prefix override (Startup.cs), so
  # this is the prefix every claim-checked object actually lands under, and what the lifecycle rule and
  # IAM policy below are scoped to.
  claim_check_prefix      = "claim-checks/"
  claim_check_bucket_name = var.claim_check_bucket_name != "" ? var.claim_check_bucket_name : "${var.project}-claim-checks-${data.aws_caller_identity.current.account_id}"

  # The Cloud Service Lambdas. Each is tagged so discovery finds it; each gets its own HTTP API so its
  # Spec UI's relative fetches resolve cleanly. orders/payments/shipping form the command chain and
  # publish events; inventory/notifications/analytics are pure event consumers (SNS/EventBridge).
  services = {
    orders        = { zip = var.orders_zip, name = "${var.project}-orders" }
    payments      = { zip = var.payments_zip, name = "${var.project}-payments" }
    shipping      = { zip = var.shipping_zip, name = "${var.project}-shipping" }
    inventory     = { zip = var.inventory_zip, name = "${var.project}-inventory" }
    notifications = { zip = var.notifications_zip, name = "${var.project}-notifications" }
    analytics     = { zip = var.analytics_zip, name = "${var.project}-analytics" }
  }

  # The OTLP endpoint Benzene's providers export to. An explicit var.otlp_endpoint wins; otherwise, when
  # the ADOT collector layer is attached, default to its in-process gRPC receiver on localhost:4317 (the
  # OpenTelemetry .NET exporter's default protocol), so attaching the layer is all it takes to get spans
  # flowing. Empty = no exporter attached at all (spans recorded but exported nowhere).
  otlp_endpoint = var.otlp_endpoint != "" ? var.otlp_endpoint : (var.adot_collector_layer_arn != "" ? "http://localhost:4317" : "")

  # OTEL_EXPORTER_OTLP_ENDPOINT points the app at the collector. When the ADOT layer is attached, also
  # override its metrics-only default config with the one shipped in the zip (traces -> awsxray), so the
  # per-middleware spans actually reach X-Ray rather than being dropped.
  # OTEL_TRACES_SAMPLER_ARG is the standard OTel ratio knob LambdaTelemetry reads (parent-based, so a
  # transaction is sampled as a whole). Set below 1 it cuts BOTH X-Ray free-tier dimensions at once:
  # traces recorded (100k/month) and traces scanned by the Mesh UI's queries (1M/month — the
  # Global-XRay-TracesAccessed line). Set var.trace_sample_rate = 1 to record every trace again.
  otlp_env = local.otlp_endpoint != "" ? merge(
    { OTEL_EXPORTER_OTLP_ENDPOINT = local.otlp_endpoint },
    { OTEL_TRACES_SAMPLER = "parentbased_traceidratio", OTEL_TRACES_SAMPLER_ARG = tostring(var.trace_sample_rate) },
    var.adot_collector_layer_arn != "" ? { OPENTELEMETRY_COLLECTOR_CONFIG_URI = "/var/task/collector.yaml" } : {}
  ) : {}

  # The ADOT collector Lambda layer, attached to every function when configured. Its default collector
  # config runs an OTLP receiver and exports traces to X-Ray (awsxray) out of the box, so Benzene's
  # per-middleware spans arrive in the same X-Ray trace view as the AWS-level segments. No auto-instrument
  # wrapper (AWS_LAMBDA_EXEC_WRAPPER) is set: these are provided.al2023 custom-runtime functions that
  # already produce their own spans, so only the collector half of the layer is used.
  collector_layers = var.adot_collector_layer_arn != "" ? [var.adot_collector_layer_arn] : []
}

# ---------------------------------------------------------------------------------------------------
# S3 bucket for the discovered registry + generated catalog artifacts.
# ---------------------------------------------------------------------------------------------------
resource "aws_s3_bucket" "artifacts" {
  bucket        = local.bucket_name
  force_destroy = true
}

# ---------------------------------------------------------------------------------------------------
# S3 bucket for the claim-check dogfood (work/archive/claim-check-plan-2026-08.md Phase 6): orders-api offloads an
# oversized payments:capture payload here (Benzene.ClaimCheck's UseClaimCheck() on that route,
# OutboundSend.ClaimChecked), payments-api hydrates it back on receive (UseClaimCheck<SqsMessageContext>(),
# enableClaimCheckHydration). DEDICATED from aws_s3_bucket.artifacts above — see claim_check_bucket_name's
# description for why (different lifecycle, different IAM audience: only orders-api/payments-api's own
# shared service role touches this bucket, never the mesh role).
# ---------------------------------------------------------------------------------------------------
resource "aws_s3_bucket" "claim_checks" {
  bucket        = local.claim_check_bucket_name
  force_destroy = true
}

# Block all public access — this bucket only ever holds transient message bodies, never anything meant
# to be served publicly (unlike aws_s3_bucket.artifacts, whose catalog artifacts back the Mesh UI's own
# fetches through the mesh's API, not direct bucket access either, but this is belt-and-braces for a
# bucket that carries raw application payloads).
resource "aws_s3_bucket_public_access_block" "claim_checks" {
  bucket = aws_s3_bucket.claim_checks.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Retention is TTL-based expiry, owned by infrastructure — Benzene.ClaimCheck.Aws.S3 never deletes an
# object itself (see IClaimCheckStore's remarks: SNS-style fan-out and at-least-once redelivery both make
# delete-on-consume unsafe). 14 days matches work/archive/claim-check-plan-2026-08.md §3's sizing rule: the TTL must
# exceed the longest possible path from send to last possible consumption — queue retention plus any DLQ
# redrive window — and SQS's own retention maxes out at 14 days, so this rule can never expire an object
# while a redelivery could still need it. Scoped to claim_check_prefix, the exact prefix the store writes
# under (see its definition above).
resource "aws_s3_bucket_lifecycle_configuration" "claim_checks" {
  bucket = aws_s3_bucket.claim_checks.id

  rule {
    id     = "expire-claim-checks"
    status = "Enabled"

    filter {
      prefix = local.claim_check_prefix
    }

    expiration {
      days = 14
    }
  }
}

# ---------------------------------------------------------------------------------------------------
# Lambda code is deployed *via S3*, not uploaded inline. A self-contained .NET publish is tens of MB,
# which exceeds the ~70 MB request cap on the direct Create/UpdateFunctionCode API
# ("RequestEntityTooLargeException"). Pushing the zip to S3 first and pointing the function at it
# (s3_bucket/s3_key) sidesteps that limit (S3-based code supports up to 250 MB unzipped).
# ---------------------------------------------------------------------------------------------------
resource "aws_s3_object" "service_code" {
  for_each = local.services
  bucket   = aws_s3_bucket.artifacts.id
  key      = "code/${each.key}.zip"
  source   = each.value.zip
  etag     = filemd5(each.value.zip)
}

resource "aws_s3_object" "mesh_code" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "code/mesh.zip"
  source = var.mesh_zip
  etag   = filemd5(var.mesh_zip)
}

# ---------------------------------------------------------------------------------------------------
# IAM: a basic-execution role for the service Lambdas, and a discovery+invoke+S3 role for the mesh.
# ---------------------------------------------------------------------------------------------------
data "aws_iam_policy_document" "lambda_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "service" {
  name               = "${var.project}-service-role"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume.json
}

resource "aws_iam_role_policy_attachment" "service_logs" {
  role       = aws_iam_role.service.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# X-Ray active tracing needs the function's role to be able to write trace segments.
resource "aws_iam_role_policy_attachment" "service_xray" {
  role       = aws_iam_role.service.name
  policy_arn = "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"
}

locals {
  # The ADOT collector's awsemf exporter writes the benzene.messages.processed counter as EMF to this
  # CloudWatch Logs group (see collector.yaml); CloudWatch extracts the Benzene/Mesh metric from it. Not
  # covered by AWSLambdaBasicExecutionRole (which scopes logs to each function's own /aws/lambda group).
  usage_emf_log_group_arn = "arn:aws:logs:${var.region}:${data.aws_caller_identity.current.account_id}:log-group:/benzene/mesh/usage"
}

# The service Lambdas' collectors write their metrics as EMF to the shared usage log group.
data "aws_iam_policy_document" "service_emf" {
  statement {
    actions   = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents", "logs:DescribeLogStreams", "logs:PutRetentionPolicy"]
    resources = [local.usage_emf_log_group_arn, "${local.usage_emf_log_group_arn}:*"]
  }
}

resource "aws_iam_role_policy" "service_emf" {
  name   = "${var.project}-service-emf"
  role   = aws_iam_role.service.id
  policy = data.aws_iam_policy_document.service_emf.json
}

resource "aws_iam_role" "mesh" {
  name               = "${var.project}-mesh-role"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume.json
}

resource "aws_iam_role_policy_attachment" "mesh_logs" {
  role       = aws_iam_role.mesh.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# X-Ray active tracing needs the mesh function's role to be able to write trace segments.
resource "aws_iam_role_policy_attachment" "mesh_xray" {
  role       = aws_iam_role.mesh.name
  policy_arn = "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"
}

data "aws_iam_policy_document" "mesh" {
  # Discover: list all functions and read their tags.
  statement {
    actions   = ["lambda:ListFunctions", "lambda:ListTags"]
    resources = ["*"]
  }
  # Interrogate: invoke the discovered service functions.
  statement {
    actions   = ["lambda:InvokeFunction"]
    resources = [for s in local.services : "arn:aws:lambda:${var.region}:${data.aws_caller_identity.current.account_id}:function:${s.name}"]
  }
  # Persist the registry + catalog artifacts.
  statement {
    actions   = ["s3:GetObject", "s3:PutObject", "s3:ListBucket"]
    resources = [aws_s3_bucket.artifacts.arn, "${aws_s3_bucket.artifacts.arn}/*"]
  }
  # Usage feed: read the benzene.messages.processed metric back from CloudWatch (these actions don't
  # support resource-level scoping, hence "*").
  statement {
    actions   = ["cloudwatch:GetMetricData", "cloudwatch:ListMetrics"]
    resources = ["*"]
  }
  # Fleet view: read traces back from X-Ray for the composite fleet read model (trace waterfall,
  # correlation search, recent flows — Benzene.Mesh.Fleet.Aws.XRay). Distinct from the
  # AWSXRayDaemonWriteAccess attachment above, which only lets the function *write* its own segments.
  # These X-Ray read actions don't support resource-level scoping, hence "*".
  statement {
    actions   = ["xray:BatchGetTraces", "xray:GetTraceSummaries"]
    resources = ["*"]
  }
  # The mesh Lambda also emits metrics, so its collector's awsemf exporter writes EMF to the usage group.
  statement {
    actions   = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents", "logs:DescribeLogStreams", "logs:PutRetentionPolicy"]
    resources = [local.usage_emf_log_group_arn, "${local.usage_emf_log_group_arn}:*"]
  }
}

resource "aws_iam_role_policy" "mesh" {
  name   = "${var.project}-mesh-policy"
  role   = aws_iam_role.mesh.id
  policy = data.aws_iam_policy_document.mesh.json
}

# ---------------------------------------------------------------------------------------------------
# The three Cloud Service Lambdas (tagged for discovery) + one HTTP API each.
# ---------------------------------------------------------------------------------------------------
resource "aws_lambda_function" "service" {
  for_each = local.services

  function_name    = each.value.name
  role             = aws_iam_role.service.arn
  s3_bucket        = aws_s3_bucket.artifacts.id
  s3_key           = aws_s3_object.service_code[each.key].key
  source_code_hash = filebase64sha256(each.value.zip)
  runtime          = "provided.al2023"
  handler          = "bootstrap"
  architectures    = [var.lambda_architecture]
  # Cold start on .NET is CPU-bound (JIT of not-yet-R2R'd reflection/serialization code + DI build),
  # and Lambda scales vCPU with memory: ~0.3 vCPU at 512 MB vs ~0.58 at 1024 (a full vCPU arrives at
  # ~1769 MB). Bumping 512 -> 1024 roughly halves that init/JIT wall time - the single biggest
  # cold-start lever once ReadyToRun is already on (see the publish step + README "Cold-start tuning").
  # Dial to 1769 for the shortest possible cold start (1 vCPU), or back to 512 to minimise cost.
  memory_size      = 1024
  timeout          = 30
  layers           = local.collector_layers

  # Always emit exactly one environment block with a non-empty variables map. A *conditional*
  # (dynamic) environment block whose values are only known after apply (the SQS queue URLs, created
  # in this same apply) trips the AWS provider's "inconsistent final plan: block count changed from
  # 0 to 1" bug. So every service gets a stable MESH_SERVICE var, merged with its chain-specific
  # queue URL where it has one (orders → payments, payments → shipping; shipping is terminal), plus
  # the shared OTLP endpoint when one is configured (so Benzene's spans/metrics reach a collector).
  environment {
    variables = merge({ MESH_SERVICE = each.key }, local.service_env[each.key], local.otlp_env)
  }

  # X-Ray active tracing — the Terraform equivalent of the "AWS X-Ray Active tracing" toggle in the
  # Lambda console, so every service gets it on deploy instead of being ticked by hand per function.
  # This captures the AWS-level segments; Benzene's per-middleware spans are exported over OTLP (set
  # var.adot_collector_layer_arn to attach the ADOT collector layer that forwards OTLP to X-Ray).
  tracing_config {
    mode = "Active"
  }

  # Discovery finds services by this tag; the mesh Lambda deliberately does NOT carry it.
  tags = { (var.discovery_tag_key) = "true" }
}

# ---------------------------------------------------------------------------------------------------
# Runtime interconnectivity — each transport used for what it's good at:
#   • SQS (point-to-point commands): orders → payments (payments:capture), payments → shipping
#     (shipping:book). Each queue triggers its service Lambda (event-source mapping).
#   • SNS (fan-out event): orders publishes order:placed → inventory AND notifications (subscriptions).
#   • EventBridge (routed integration events on a custom bus): payments publishes payment:captured,
#     shipping publishes shipping:dispatched → routed by rule to notifications/inventory/analytics.
# Env vars hand each producer its target (queue URL / topic ARN / bus name); consumers just receive.
# ---------------------------------------------------------------------------------------------------
locals {
  service_env = {
    orders = {
      PAYMENTS_QUEUE_URL       = aws_sqs_queue.payments.url
      ORDER_PLACED_TOPIC_ARN   = aws_sns_topic.order_placed.arn
      # The outbox pair (work/archive/outbox-plan-2026-08.md Phase 3): the order row + the atomically-committed
      # captured envelopes for payments:capture/order:placed.
      ORDERS_TABLE_NAME        = aws_dynamodb_table.orders.name
      ORDERS_OUTBOX_TABLE_NAME = aws_dynamodb_table.orders_outbox.name
      # The claim-check dogfood's sending side (work/archive/claim-check-plan-2026-08.md Phase 6): offloads an
      # oversized payments:capture send here instead of inlining it on the SQS message.
      CLAIM_CHECK_BUCKET       = aws_s3_bucket.claim_checks.id
    }
    payments = {
      SHIPPING_QUEUE_URL              = aws_sqs_queue.shipping.url
      EVENT_BUS_NAME                  = aws_cloudwatch_event_bus.bus.name
      # The consume side of the outbox+idempotency pair: dedups payments:capture redeliveries.
      PAYMENTS_IDEMPOTENCY_TABLE_NAME = aws_dynamodb_table.payments_idempotency.name
      # The claim-check dogfood's hydrating side: resolves the benzene-claim-check reference back to
      # the real body before the handler runs. Same bucket orders-api writes to.
      CLAIM_CHECK_BUCKET               = aws_s3_bucket.claim_checks.id
    }
    shipping      = { EVENT_BUS_NAME = aws_cloudwatch_event_bus.bus.name }
    inventory     = {}
    notifications = {}
    analytics     = {}
  }

  # SNS fan-out: order:placed is delivered to each of these service Lambdas.
  sns_order_placed_subscribers = toset(["inventory", "notifications"])

  # EventBridge routing: one rule per integration event (matched on detail-type = the Benzene topic),
  # fanned out to the listed consumer Lambdas. Rule keys are slugs (no ':') for valid resource names.
  eventbridge_rules = {
    payment_captured    = { detail_type = "payment:captured", targets = ["notifications", "analytics"] }
    shipping_dispatched = { detail_type = "shipping:dispatched", targets = ["inventory", "notifications", "analytics"] }
  }

  # Flatten {rule → [targets]} to individual (rule, service) pairs for the per-target resources.
  eventbridge_targets = merge([
    for rule_key, rule in local.eventbridge_rules : {
      for svc in rule.targets : "${rule_key}-${svc}" => { rule_key = rule_key, service = svc }
    }
  ]...)
}

# --- SQS: the point-to-point command hops -----------------------------------------------------------
resource "aws_sqs_queue" "payments" {
  name                       = "${var.project}-payments-queue"
  visibility_timeout_seconds = 60
}

resource "aws_sqs_queue" "shipping" {
  name                       = "${var.project}-shipping-queue"
  visibility_timeout_seconds = 60
}

resource "aws_lambda_event_source_mapping" "payments" {
  event_source_arn = aws_sqs_queue.payments.arn
  function_name    = aws_lambda_function.service["payments"].arn
  batch_size       = 1
}

resource "aws_lambda_event_source_mapping" "shipping" {
  event_source_arn = aws_sqs_queue.shipping.arn
  function_name    = aws_lambda_function.service["shipping"].arn
  batch_size       = 1
}

# --- SNS: the order:placed fan-out ------------------------------------------------------------------
resource "aws_sns_topic" "order_placed" {
  name = "${var.project}-order-placed"
}

# Deliver the topic straight to each subscriber Lambda (SNS → Lambda), and allow SNS to invoke them.
resource "aws_sns_topic_subscription" "order_placed" {
  for_each  = local.sns_order_placed_subscribers
  topic_arn = aws_sns_topic.order_placed.arn
  protocol  = "lambda"
  endpoint  = aws_lambda_function.service[each.key].arn
}

resource "aws_lambda_permission" "sns_invoke" {
  for_each      = local.sns_order_placed_subscribers
  statement_id  = "AllowSnsInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.service[each.key].function_name
  principal     = "sns.amazonaws.com"
  source_arn    = aws_sns_topic.order_placed.arn
}

# --- EventBridge: the routed integration events on a dedicated bus -----------------------------------
resource "aws_cloudwatch_event_bus" "bus" {
  name = "${var.project}-bus"
}

resource "aws_cloudwatch_event_rule" "integration" {
  for_each       = local.eventbridge_rules
  name           = "${var.project}-${each.key}"
  event_bus_name = aws_cloudwatch_event_bus.bus.name
  # The Benzene EventBridge sender maps the topic onto detail-type, so route on that.
  event_pattern = jsonencode({ "detail-type" = [each.value.detail_type] })
}

resource "aws_cloudwatch_event_target" "integration" {
  for_each       = local.eventbridge_targets
  rule           = aws_cloudwatch_event_rule.integration[each.value.rule_key].name
  event_bus_name = aws_cloudwatch_event_bus.bus.name
  target_id      = each.value.service
  arn            = aws_lambda_function.service[each.value.service].arn
}

resource "aws_lambda_permission" "eventbridge_invoke" {
  for_each      = local.eventbridge_targets
  statement_id  = "AllowEventBridge-${each.key}"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.service[each.value.service].function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.integration[each.value.rule_key].arn
}

# --- DynamoDB: the outbox pair (work/archive/outbox-plan-2026-08.md Phase 3) + the consume-side idempotency table ----
# orders-api dogfoods the transactional outbox: `orders` is its own state table, `orders-outbox` is the
# captured-envelope table Benzene.Outbox.DynamoDb writes to and streams from. payments-api is the
# consume side of the pair: `payments-idempotency` dedups the at-least-once redeliveries the outbox
# relay can produce on payments:capture.
resource "aws_dynamodb_table" "orders" {
  name         = "${var.project}-orders"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "id"

  attribute {
    name = "id"
    type = "S"
  }
}

# Table shape required by Benzene.Outbox.DynamoDb (see src/Benzene.Outbox.DynamoDb/CLAUDE.md "Table
# shape"): partition key `id`; a sparse GSI `pending-index` (gsiPk/gsiSk, ProjectionType ALL) the
# sweeper queries; native TTL on `expiresAt`, set only once an envelope dispatches. Streams enabled with
# NEW_IMAGE so the event-source mapping below can hand INSERT records to OutboxStreamDispatchMessageHandler.
resource "aws_dynamodb_table" "orders_outbox" {
  name             = "${var.project}-orders-outbox"
  billing_mode     = "PAY_PER_REQUEST"
  hash_key         = "id"
  stream_enabled   = true
  stream_view_type = "NEW_IMAGE"

  attribute {
    name = "id"
    type = "S"
  }
  attribute {
    name = "gsiPk"
    type = "S"
  }
  attribute {
    name = "gsiSk"
    type = "S"
  }

  global_secondary_index {
    name            = "pending-index"
    hash_key        = "gsiPk"
    range_key       = "gsiSk"
    projection_type = "ALL"
  }

  ttl {
    attribute_name = "expiresAt"
    enabled        = true
  }
}

# Table shape required by Benzene.Idempotency.DynamoDb: partition key `pk`; native TTL on `expiresAt`.
resource "aws_dynamodb_table" "payments_idempotency" {
  name         = "${var.project}-payments-idempotency"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "pk"

  attribute {
    name = "pk"
    type = "S"
  }

  ttl {
    attribute_name = "expiresAt"
    enabled        = true
  }
}

# Streams dispatch: near-real-time half of the relay pair (work/archive/outbox-plan-2026-08.md §2.5 option 1). The
# event-source mapping polls with the orders Lambda's OWN execution role (aws_iam_role.service) — see
# the service_dynamodb IAM policy below for the stream-read grant. maximum_retry_attempts bounds how
# long a persistently-failing dispatch can block this shard before the mapping gives up on that batch
# and moves on — the scheduled sweep (below) is the backstop for whatever's left Pending after that.
resource "aws_lambda_event_source_mapping" "orders_outbox_stream" {
  event_source_arn       = aws_dynamodb_table.orders_outbox.stream_arn
  function_name          = aws_lambda_function.service["orders"].arn
  starting_position       = "LATEST"
  batch_size              = 1
  maximum_retry_attempts  = 3
}

# Scheduled sweep: the required backstop (work/archive/outbox-plan-2026-08.md §2.5 option 2) — retries what the stream
# missed, parks anything past MaxAttempts, and (on a store with no native TTL) would own retention. Same
# shape as the mesh's own `aggregate` schedule below: an EventBridge rule invoking the Lambda directly,
# routed by detail-type to the app-chosen `orders:outbox-sweep` topic (never `benzene:*` — reserved
# topics are spec surface).
resource "aws_cloudwatch_event_rule" "orders_outbox_sweep" {
  name                = "${var.project}-orders-outbox-sweep"
  schedule_expression = var.orders_outbox_sweep_schedule
}

resource "aws_cloudwatch_event_target" "orders_outbox_sweep" {
  rule      = aws_cloudwatch_event_rule.orders_outbox_sweep.name
  target_id = "orders"
  arn       = aws_lambda_function.service["orders"].arn
  # See the aggregate target below for why `detail` must be a JSON object, not a string.
  input = jsonencode({ "detail-type" = "orders:outbox-sweep", "source" = "benzene.outbox", "detail" = {} })
}

resource "aws_lambda_permission" "orders_outbox_sweep_events" {
  statement_id  = "AllowEventBridgeInvokeOutboxSweep"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.service["orders"].function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.orders_outbox_sweep.arn
}

# --- IAM: the shared service role's producer permissions --------------------------------------------
# The shared service role can send to both queues (as a producer) and consume them (the event-source
# mapping polls with the function's role), publish the SNS topic, and put events on the custom bus.
data "aws_iam_policy_document" "service_sqs" {
  statement {
    actions = [
      "sqs:SendMessage",
      "sqs:ReceiveMessage",
      "sqs:DeleteMessage",
      "sqs:GetQueueAttributes",
    ]
    resources = [aws_sqs_queue.payments.arn, aws_sqs_queue.shipping.arn]
  }
  statement {
    # sns:Publish is the data path; sns:GetTopicAttributes is the read-only reachability probe the
    # auto-wired SnsHealthCheck makes — without it the health check reports a persistent
    # AuthorizationError (surfaced on the Mesh UI with RequiredPermission naming this action).
    actions   = ["sns:Publish", "sns:GetTopicAttributes"]
    resources = [aws_sns_topic.order_placed.arn]
  }
  statement {
    # events:PutEvents is the data path; events:DescribeEventBus is the read-only reachability probe
    # the auto-wired EventBridgeHealthCheck makes (EventBridge has no dry-run PutEvents, and a real
    # PutEvents probe would fire live rules) — without it the check reports a persistent
    # AccessDeniedException (HTTP 400) and the service shows unhealthy on the Mesh UI.
    actions   = ["events:PutEvents", "events:DescribeEventBus"]
    resources = [aws_cloudwatch_event_bus.bus.arn]
  }
}

resource "aws_iam_role_policy" "service_sqs" {
  name   = "${var.project}-service-messaging"
  role   = aws_iam_role.service.id
  policy = data.aws_iam_policy_document.service_sqs.json
}

# The shared service role's DynamoDB permissions: item-level access to the three outbox/idempotency
# tables (only orders/payments actually use them; the shared role is broad by design in this example,
# same pattern as service_sqs above granting both queues to every service's role), plus the stream-read
# actions the orders_outbox_stream event-source mapping needs (it polls with the FUNCTION's own role,
# not a separate one).
data "aws_iam_policy_document" "service_dynamodb" {
  statement {
    actions = [
      "dynamodb:PutItem",
      "dynamodb:GetItem",
      "dynamodb:UpdateItem",
      "dynamodb:Query",
    ]
    resources = [
      aws_dynamodb_table.orders.arn,
      aws_dynamodb_table.orders_outbox.arn,
      "${aws_dynamodb_table.orders_outbox.arn}/index/*",
      aws_dynamodb_table.payments_idempotency.arn,
    ]
  }
  # TransactWriteItems (the atomic order-row + captured-envelopes commit) needs its own action
  # alongside the item-level ones above.
  statement {
    actions   = ["dynamodb:TransactWriteItems"]
    resources = [aws_dynamodb_table.orders.arn, aws_dynamodb_table.orders_outbox.arn]
  }
  statement {
    actions = [
      "dynamodb:DescribeStream",
      "dynamodb:GetRecords",
      "dynamodb:GetShardIterator",
      "dynamodb:ListStreams",
    ]
    resources = [aws_dynamodb_table.orders_outbox.stream_arn]
  }
}

resource "aws_iam_role_policy" "service_dynamodb" {
  name   = "${var.project}-service-dynamodb"
  role   = aws_iam_role.service.id
  policy = data.aws_iam_policy_document.service_dynamodb.json
}

# The shared service role's claim-check permissions, scoped to the bucket's claim_check_prefix path
# only (never the bucket root). Only orders-api PUTs (offloading a payments:capture send) and only
# payments-api GETs (hydrating on receive) — but both actions are granted to the ONE shared service role
# both services run under, same broad-by-design posture as service_sqs/service_dynamodb above (the
# comments on those explain why: this example role is intentionally not split per-service). A real
# multi-role deployment would give orders-api put-only and payments-api get-only.
data "aws_iam_policy_document" "service_claim_check" {
  statement {
    actions   = ["s3:PutObject", "s3:GetObject"]
    resources = ["${aws_s3_bucket.claim_checks.arn}/${local.claim_check_prefix}*"]
  }
}

resource "aws_iam_role_policy" "service_claim_check" {
  name   = "${var.project}-service-claim-check"
  role   = aws_iam_role.service.id
  policy = data.aws_iam_policy_document.service_claim_check.json
}

# ---------------------------------------------------------------------------------------------------
# The mesh Lambda (NOT tagged for discovery) + its HTTP API + the aggregation schedule.
# ---------------------------------------------------------------------------------------------------
resource "aws_lambda_function" "mesh" {
  function_name    = "${var.project}-mesh"
  role             = aws_iam_role.mesh.arn
  s3_bucket        = aws_s3_bucket.artifacts.id
  s3_key           = aws_s3_object.mesh_code.key
  source_code_hash = filebase64sha256(var.mesh_zip)
  runtime          = "provided.al2023"
  handler          = "bootstrap"
  architectures    = [var.lambda_architecture]
  memory_size      = 1024
  timeout          = 60
  layers           = local.collector_layers

  # #73 (WP-E): MeshAggregateHandler (Mesh/MeshAggregateHandler.cs) runs the SAME aggregation pass -
  # discover, write registry.json, interrogate, write the catalog - from TWO triggers on this one
  # function: the EventBridge schedule below, and the on-demand POST /mesh/refresh (behind
  # UseMeshRefreshGuard on the API Gateway route). Unlike the other four mesh examples (AzureMesh,
  # AzureFunctionsMesh, K8sMesh, GoogleCloudMesh), which each run as one long-lived process where an
  # in-process semaphore (MeshAggregationPass's single-writer gate) can serialize concurrent callers,
  # a Lambda's EventBridge invocation and its API-Gateway-triggered invocation execute in SEPARATE
  # execution environments - no in-process lock, semaphore, or static field is shared between them, so
  # nothing in the .NET code can prevent two passes from running concurrently and racing on the same
  # S3 keys (registry.json, manifest.json, services/*.json - all unconditional PutObject, no
  # conditional-write/ETag guard).
  #
  # WHAT THIS DOES: caps the mesh Lambda to exactly one concurrent execution across BOTH triggers - a
  # cheap platform-level serializer requiring no new infrastructure. A second invocation that would
  # exceed the reservation while one is in flight is throttled (EventBridge retries per its own retry
  # policy; the refresh route's caller sees a Lambda throttling error, which the browser reports as a
  # failed refresh, not a corrupted catalog).
  #
  # WHAT THIS DOES NOT DO: it is not a queue and not a distributed lock with fairness/ordering
  # guarantees - it is a hard concurrency ceiling, the same "not a distributed lock" caveat
  # MeshRefreshGuardMiddleware's own remarks give its throttle (see that class's XML docs). A burst of
  # near-simultaneous triggers can still throttle a legitimate request rather than queueing it, and a
  # long-running pass (this function's `timeout` above) holds the single slot for its full duration,
  # so the scheduled pass and an operator's on-demand refresh compete for the same one slot rather than
  # running independently. If true single-flight semantics (queueing instead of throttling, ordering
  # guarantees) are ever needed, the fuller fix is an S3 conditional-write/lease (e.g. a
  # `registry.lock` object written with `If-None-Match: *` before a pass starts, removed after) - NOT
  # adopting `MeshAggregationPass`'s in-process semaphore here, which would compile and appear to help
  # but cannot cross the Lambda execution-environment boundary this finding is actually about.
  reserved_concurrent_executions = 1

  environment {
    variables = merge({
      MESH_ARTIFACT_BUCKET = aws_s3_bucket.artifacts.id
      MESH_ARTIFACT_PREFIX = "mesh"
      # The lookback window the CloudWatch usage source counts over (and the window the Mesh UI shows).
      MESH_USAGE_WINDOW_HOURS = tostring(var.usage_window_hours)
      # Option B admin-managed seed (work/mesh-external-service-discovery-scope-2026-08.md): services
      # outside this account entirely, unioned into the discovered registry (winning on a name clash) by
      # Mesh/Startup.cs's ParseExtraServices, reusing the exact mesh.json shape MeshRegistryJson already
      # reads/writes. Always set, even for the default empty list, so the Lambda's env is deterministic
      # across applies — an empty services array parses to a no-op seed, byte-identical to unset.
      MESH_EXTRA_SERVICES = jsonencode({
        services = [for s in var.mesh_extra_services : {
          name      = s.name
          specUrl   = s.specUrl
          healthUrl = s.healthUrl
        }]
      })
      # Google OAuth login gate (Benzene.Mesh.Auth.Oidc, wired in Mesh/Startup.cs) - see
      # examples/AwsMesh/README.md's "Auth setup" section. The signing key is Terraform-generated
      # (random_id.mesh_oidc_signing_key above), never hand-typed.
      GOOGLE_OAUTH_CLIENT_ID     = var.google_oauth_client_id
      GOOGLE_OAUTH_CLIENT_SECRET = var.google_oauth_client_secret
      MESH_OIDC_SIGNING_KEY      = random_id.mesh_oidc_signing_key.b64_url
      MESH_ALLOWED_EMAILS        = join(",", var.mesh_allowed_emails)
      # App-level throttle on POST /mesh/refresh (UseMeshRefreshGuard). Complements — never replaces —
      # the API Gateway rate/burst limits on the stage below: those cap requests before a Lambda
      # invocation is billed, this caps how often the expensive pass behind one actually runs.
      MESH_REFRESH_MIN_INTERVAL_SECONDS = tostring(var.refresh_min_interval_seconds)
      # THE GATE. MeshDispatchGate reads this and refuses to dispatch when it is unset or Production -
      # deliberately, because a dispatch runs a real handler with real side-effects. Setting it is what
      # turns the Test Console's Send button from decoration into a working control on this estate.
      DOTNET_ENVIRONMENT = var.mesh_environment
      # App-level bounds on POST /mesh/dispatch (UseMeshDispatchGuard). Second layer, not the first:
      # these count in this process, so they bound a warm instance rather than the fleet. The edge
      # throttle on the dispatch route below is what holds across every instance.
      MESH_DISPATCH_MAX_PER_MINUTE            = tostring(var.mesh_dispatch_max_per_minute)
      MESH_DISPATCH_MAX_PER_TARGET_PER_MINUTE = tostring(var.mesh_dispatch_max_per_target_per_minute)
    }, local.otlp_env)
  }

  # X-Ray active tracing for the mesh Lambda too, so its scheduled aggregation run shows up as a trace
  # (and, with the ADOT collector layer wired via var.adot_collector_layer_arn, its per-middleware
  # spans alongside it).
  tracing_config {
    mode = "Active"
  }
}

# One HTTP API per Lambda: a $default catch-all proxies the full path through, so each service's
# /benzene/spec-ui and the mesh's /mesh-ui (with their relative fetches) resolve against the API root.
resource "aws_apigatewayv2_api" "service" {
  for_each      = local.services
  name          = "${each.value.name}-api"
  protocol_type = "HTTP"
}

resource "aws_apigatewayv2_integration" "service" {
  for_each               = local.services
  api_id                 = aws_apigatewayv2_api.service[each.key].id
  integration_type       = "AWS_PROXY"
  integration_uri        = aws_lambda_function.service[each.key].invoke_arn
  payload_format_version = "1.0" # matches what Benzene.Aws.Lambda.ApiGateway parses
}

resource "aws_apigatewayv2_route" "service" {
  for_each  = local.services
  api_id    = aws_apigatewayv2_api.service[each.key].id
  route_key = "$default"
  target    = "integrations/${aws_apigatewayv2_integration.service[each.key].id}"
}

resource "aws_apigatewayv2_stage" "service" {
  for_each    = local.services
  api_id      = aws_apigatewayv2_api.service[each.key].id
  name        = "$default"
  auto_deploy = true
}

resource "aws_lambda_permission" "service_api" {
  for_each      = local.services
  statement_id  = "AllowApiGatewayInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.service[each.key].function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.service[each.key].execution_arn}/*/*"
}

resource "aws_apigatewayv2_api" "mesh" {
  name          = "${var.project}-mesh-api"
  protocol_type = "HTTP"
}

resource "aws_apigatewayv2_integration" "mesh" {
  api_id                 = aws_apigatewayv2_api.mesh.id
  integration_type       = "AWS_PROXY"
  integration_uri        = aws_lambda_function.mesh.invoke_arn
  payload_format_version = "1.0"
}

# THE SEND ROUTE, DECLARED EXPLICITLY. Everything else on this API is served by the $default
# catch-all below, and dispatch could have been too - but a stage's `route_settings` can only attach
# to a route that exists, and this is the one route that needs a ceiling of its own. Declaring it
# changes no behaviour (it points at the same Lambda integration); it exists so the throttle has
# something to hold on to.
resource "aws_apigatewayv2_route" "mesh_dispatch" {
  api_id    = aws_apigatewayv2_api.mesh.id
  route_key = "POST /mesh/dispatch"
  target    = "integrations/${aws_apigatewayv2_integration.mesh.id}"
}

resource "aws_apigatewayv2_route" "mesh" {
  api_id    = aws_apigatewayv2_api.mesh.id
  route_key = "$default"
  target    = "integrations/${aws_apigatewayv2_integration.mesh.id}"
}

resource "aws_apigatewayv2_stage" "mesh" {
  api_id      = aws_apigatewayv2_api.mesh.id
  name        = "$default"
  auto_deploy = true

  # Cost/abuse protection at the EDGE, which is the only place it can be free: API Gateway refuses
  # excess requests with its own 429 before the Lambda is invoked, so a flood costs no invocations, no
  # X-Ray traces, no S3 reads, and no fan-out to the six service Lambdas. The app-level guard on
  # POST /mesh/refresh (MESH_REFRESH_MIN_INTERVAL_SECONDS above) is the second, complementary layer —
  # it bounds how often the expensive pass runs, but only after the invoke has already been billed.
  # Applied to $default, so it covers every route on this API (the Mesh UI, the catalog artifacts, the
  # /benzene/invoke fleet poll, the auth routes, and /mesh/refresh) rather than only the one endpoint.
  default_route_settings {
    throttling_rate_limit  = var.mesh_api_throttling_rate_limit
    throttling_burst_limit = var.mesh_api_throttling_burst_limit
  }

  # THE SEND ROUTE, HELD TIGHTER THAN THE REST. Everything else on this API reads; this one route
  # fires a caller's payload into a real service handler, so it gets its own, much lower ceiling.
  #
  # It is a separate route from the fleet poll for exactly this reason. While dispatch and the
  # catalogue queries shared /benzene/invoke there was no way to throttle sending without also
  # throttling reading the estate - and a limit that makes the dashboard stutter is a limit somebody
  # turns off.
  #
  # This is also the layer that carries the real guarantee. The mesh's own per-identity limiter counts
  # in memory, so on a host that scales to N instances it bounds one warm instance; API Gateway counts
  # across all of them, and refuses before the invoke is billed.
  route_settings {
    # Referencing the route resource's own attribute (not a hardcoded literal) so Terraform's
    # dependency graph forces aws_apigatewayv2_route.mesh_dispatch to exist before this stage is
    # created - a bare string here has no graph edge to that resource, so the stage's creation could
    # race the route's and fail with "Unable to find Route by key ... within the provided
    # RouteSettings" whenever the stage happened to land first.
    route_key              = aws_apigatewayv2_route.mesh_dispatch.route_key
    throttling_rate_limit  = var.mesh_dispatch_throttling_rate_limit
    throttling_burst_limit = var.mesh_dispatch_throttling_burst_limit
  }
}

resource "aws_lambda_permission" "mesh_api" {
  statement_id  = "AllowApiGatewayInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.mesh.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.mesh.execution_arn}/*/*"
}

# Scheduled aggregation: fire the mesh Lambda with a constant payload the Benzene EventBridge adapter
# routes to the `mesh:aggregate` handler (detail-type = the topic).
resource "aws_cloudwatch_event_rule" "aggregate" {
  name                = "${var.project}-aggregate"
  schedule_expression = var.aggregate_schedule
}

resource "aws_cloudwatch_event_target" "aggregate" {
  rule      = aws_cloudwatch_event_rule.aggregate.name
  target_id = "mesh"
  arn       = aws_lambda_function.mesh.arn
  # `detail` must be a JSON OBJECT, not a string. The Benzene EventBridge adapter reads the body as
  # detail.GetRawText() and deserializes it into the handler's request type (Void here). An empty
  # object ({}) deserializes cleanly; the string "{}" deserializes as a JSON string and the mapper
  # rejects it — surfacing as a 400 on every scheduled fire (visible in the fleet once the invocation
  # gets an X-Ray-compatible trace id). This matches the shape of a real EventBridge-delivered event,
  # whose `detail` is always an object.
  #
  # The detail-type MUST equal the handler's registered topic EXACTLY: EventBridgeMessageTopicGetter
  # returns `new Topic(context.Event.DetailType)` verbatim, with no prefix tolerance, and
  # MeshAggregateHandler is [Message("benzene:mesh:aggregate")]. The reserved-topic rename onto the
  # `benzene:` prefix updated the handler and missed this line, so every scheduled fire since then
  # resolved no handler and silently did nothing — which is why a freshly-deployed mesh kept 404ing
  # on manifest.json until someone POSTed /mesh/refresh by hand.
  input = jsonencode({ "detail-type" = "benzene:mesh:aggregate", "source" = "benzene.mesh", "detail" = {} })
}

resource "aws_lambda_permission" "mesh_events" {
  statement_id  = "AllowEventBridgeInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.mesh.function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.aggregate.arn
}
