namespace Benzene.CodeGen.Cli.Core;

public static class Constants
{
    public const string ProfileDescription = "Profile used to connect to AWS";
    public const string Profile = "profile";
    public const string LambdaName = "lambda-name";
    public const string LambdaNameDescription = "The name of the lambda running the service";
    public const string Output = "output";
    public const string OutputDefault = "client";
    public const string OutputDescription = "The build output: 'client' (one client for the whole service), 'topic-client' (a small self-contained client per topic), 'message-handlers' or 'readme'";
    public const string Directory = "directory";
    public const string DirectoryDescription = "The destination directory for the code. Leave empty for current directory.";
    public const string File = "file";
    public const string FileDescription = "Path to a benzene spec JSON file to read instead of fetching the spec from a lambda";
    public const string Type = "type";
    public const string TypeDefault = "benzene";
    public const string TypeDescription = "The document type, either 'benzene', 'openapi' or 'asyncapi'";
    public const string Format = "format";
    public const string FormatDefault = "json";
    public const string FormatDescription = "The document format, either 'yaml' or 'json'";
    public const string Url = "url";
    public const string UrlDescription = "The base URL of a Benzene Cloud Service, e.g. https://orders.example.com. For 'profile-check' the service is probed for R1-R8 conformance; for 'spec'/'build' its spec document is fetched from {url}/benzene/spec instead of invoking a lambda.";
    public const string Mesh = "mesh";
    public const string MeshDescription = "The URL of a mesh manifest.json to resolve the service's spec from, e.g. https://mesh.example.com/manifest.json. The service's services/{name}.json snapshot is resolved relative to this URL, mirroring the Mesh UI. Requires --service.";
    public const string Service = "service";
    public const string ServiceDescription = "The service name to look up in the mesh manifest (required with --mesh)";
    public const string ServiceName = "service-name";
    public const string ServiceNameDescription = "Overrides the generated service name / namespace root for 'build'. Defaults when not given: --mesh uses the mesh service name; --file uses the spec document's own title, else the file's stem; --url uses the host's first label; --lambda-name keeps deriving the name from the lambda name.";
    public const string InvokePath = "invoke-path";
    public const string InvokePathDescription = "Overrides the wire-envelope endpoint path probed for R4/R6. Defaults to /benzene/invoke";
    public const string SpecPath = "spec-path";
    public const string SpecPathDescription = "Overrides the derived spec endpoint path probed for R5. Defaults to /benzene/spec";
    public const string HealthPath = "health-path";
    public const string HealthPathDescription = "Overrides the health endpoint path probed for R3. Defaults to /benzene/health";
    public const string NoTraceParentProbe = "no-traceparent-probe";
    public const string NoTraceParentProbeDescription = "Skips the R8 bonus traceparent header sent with the R4/R6 probe requests";
    public const string Baseline = "baseline";
    public const string BaselineDescription = "Path to the baseline (previous) Benzene spec JSON file";
    public const string Current = "current";
    public const string CurrentDescription = "Path to the current Benzene spec JSON file to compare against the baseline";
    public const string FailOn = "fail-on";
    public const string FailOnDefault = "breaking";
    public const string FailOnDescription = "The change severity that fails the command: 'breaking', 'warning' or 'none'. Exits non-zero when a change at or above this level is found.";
    public const string WarnOnly = "warn-only";
    public const string WarnOnlyDescription = "Equivalent to --fail-on none: reports every change but always exits 0";
    public const string DiffFormatDefault = "text";
    public const string DiffFormatDescription = "The diff report format, either 'text' (human-readable, one line per change) or 'json' (the serialized compatibility report)";
    public const string Namespace = "namespace";
    public const string NamespaceDescription = "Overrides the generated namespace for 'build' (used exactly, with no magic suffix, across the client class, its interface and its DTOs). 'topic-client' still appends .{ClientName} per client below this root. Defaults when not given: today's derivation from --lambda-name/--service-name is unchanged.";
    public const string Topics = "topics";
    public const string TopicsDescription = "A comma-delimited topic include-list for 'build' (e.g. 'order:create,order:cancel'). Only these topics (plus the always-exempt benzene:healthcheck) are generated; a named topic the document doesn't have fails the build. Defaults to every non-reserved topic in the document when not given.";
}
